// <auto-generated />
using System;
using Irimia_web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Irimia_web.Migrations
{
    [DbContext(typeof(Irimia_webContext))]
    partial class Irimia_webContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Irimia_web.Models.Medic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Medic");
                });

            modelBuilder.Entity("Irimia_web.Models.Orar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Zi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Orar");
                });

            modelBuilder.Entity("Irimia_web.Models.Pacient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localitate")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Nume")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prenume")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pacient");
                });

            modelBuilder.Entity("Irimia_web.Models.Programare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("DataProgramare")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PacientID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiciuID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PacientID");

                    b.HasIndex("ServiciuID");

                    b.ToTable("Programare");
                });

            modelBuilder.Entity("Irimia_web.Models.Serviciu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("MedicID")
                        .HasColumnType("int");

                    b.Property<int?>("OrarID")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.HasIndex("MedicID");

                    b.HasIndex("OrarID");

                    b.ToTable("Serviciu");
                });

            modelBuilder.Entity("Irimia_web.Models.Specialitate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeSpecialitate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Specialitate");
                });

            modelBuilder.Entity("Irimia_web.Models.SpecialitateServiciu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ServiciuID")
                        .HasColumnType("int");

                    b.Property<int>("SpecialitateID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ServiciuID");

                    b.HasIndex("SpecialitateID");

                    b.ToTable("SpecialitateServiciu");
                });

            modelBuilder.Entity("Irimia_web.Models.Programare", b =>
                {
                    b.HasOne("Irimia_web.Models.Pacient", "Pacient")
                        .WithMany("Programari")
                        .HasForeignKey("PacientID");

                    b.HasOne("Irimia_web.Models.Serviciu", "Serviciu")
                        .WithMany()
                        .HasForeignKey("ServiciuID");

                    b.Navigation("Pacient");

                    b.Navigation("Serviciu");
                });

            modelBuilder.Entity("Irimia_web.Models.Serviciu", b =>
                {
                    b.HasOne("Irimia_web.Models.Medic", "Medic")
                        .WithMany("Servicii")
                        .HasForeignKey("MedicID");

                    b.HasOne("Irimia_web.Models.Orar", "Orar")
                        .WithMany("Servicii")
                        .HasForeignKey("OrarID");

                    b.Navigation("Medic");

                    b.Navigation("Orar");
                });

            modelBuilder.Entity("Irimia_web.Models.SpecialitateServiciu", b =>
                {
                    b.HasOne("Irimia_web.Models.Serviciu", "Serviciu")
                        .WithMany("SpecialitatiServiciu")
                        .HasForeignKey("ServiciuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Irimia_web.Models.Specialitate", "Specialitate")
                        .WithMany("SpecialitatiServiciu")
                        .HasForeignKey("SpecialitateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serviciu");

                    b.Navigation("Specialitate");
                });

            modelBuilder.Entity("Irimia_web.Models.Medic", b =>
                {
                    b.Navigation("Servicii");
                });

            modelBuilder.Entity("Irimia_web.Models.Orar", b =>
                {
                    b.Navigation("Servicii");
                });

            modelBuilder.Entity("Irimia_web.Models.Pacient", b =>
                {
                    b.Navigation("Programari");
                });

            modelBuilder.Entity("Irimia_web.Models.Serviciu", b =>
                {
                    b.Navigation("SpecialitatiServiciu");
                });

            modelBuilder.Entity("Irimia_web.Models.Specialitate", b =>
                {
                    b.Navigation("SpecialitatiServiciu");
                });
#pragma warning restore 612, 618
        }
    }
}
